### Variables 
@apiurl = http://127.0.0.1:8000/graphql?query={produtos{id}}

### GET users
GET {{apiurl}}

### POST users
POST {{apiurl}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

produtos{
}

### GET categories
GET {{apiurl}}/produtos HTTP/1.1